<?php
/**
 * @SWG\Definition(
 *     definition="User",
 *     required={"id", "name", "email", "tel_number","age", "gender", "balance",
 *     "promo_code_first", "promo_code_second"},
 *     @SWG\Property(
 *         property="id",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="name",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="email",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="tel_number",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="age",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="gender",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="balance",
 *         type="number"
 *     ),
 *     @SWG\Property(
 *         property="promo_code_first",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="promo_code_second",
 *         type="string"
 *     ),
 *
 * ),
 * @SWG\Definition(
 *     definition="Task",
 *     required={"id", "package_name", "title", "image_url", "description", "tracking_link", "duration", "award", "daily_award",
 *     "type", "days", "time", "keywords", "rate_type", "rate_keywords"},
 *     @SWG\Property(
 *         property="id",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="package_name",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="title",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="image_url",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="description",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="tracking_link",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="duration",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="award",
 *         type="number"
 *     ),
 *      @SWG\Property(
 *         property="daily_award",
 *         type="number"
 *     ),
 *     @SWG\Property(
 *         property="type",
 *         type="integer"
 *     ),
 *      @SWG\Property(
 *         property="days",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="time",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="keywords",
 *         type="array",
 *         @SWG\Items(type="string")
 *     ),
 *     @SWG\Property(
 *         property="rate_type",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="rate_keywords",
 *         type="array",
 *         @SWG\Items(type="string")
 *     ),
 * ),
 * @SWG\Definition(
 *     definition="HistoryTask",
 *     required={"id", "title", "image_url", "pivot"},
 *     @SWG\Property(
 *         property="id",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="title",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="image_url",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="pivot",
 *         ref="#/definitions/Pivot_h_t"
 *     ),
 *
 * ),
 * @SWG\Definition(
 *     definition="Pivot_h_t",
 *     required={"date", "earned"},
 *     @SWG\Property(
 *         property="date",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="earned",
 *         type="number"
 *     ),
 *
 * ),
 * @SWG\Definition(
 *     definition="Token",
 *     required={"token", "promo_code_first", "promo_code_second", "is_new"},
 *     @SWG\Property(
 *         property="token",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="promo_code_first",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="promo_code_second",
 *         type="string"
 *     ),
 *
 * ),
 * @SWG\Definition(
 *     definition="Balance",
 *     required={"referral_balance", "balance", "during", "paid"},
 *     @SWG\Property(
 *         property="referral_balance",
 *         type="number"
 *     ),
 *     @SWG\Property(
 *         property="balance",
 *         type="number"
 *     ),
 *     @SWG\Property(
 *         property="during",
 *         type="number"
 *     ),
 *     @SWG\Property(
 *         property="paid",
 *         type="number"
 *     ),
 *
 * ),
 * @SWG\Definition(
 *     definition="Link",
 *     required={"text", "link", "award"},
 *     @SWG\Property(
 *         property="text",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="link",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="award",
 *         type="number"
 *     ),
 *
 * ),
 * @SWG\Definition(
 *     definition="Tasks for Top",
 *     required={"tasks","links", "referral", "videos", "partners", "balance", "entertainment"},
 *     @SWG\Property(
 *         property="tasks",
 *         type="array",
 *         @SWG\Items(ref="#/definitions/Task")
 *     ),
 *     @SWG\Property(
 *         property="links",
 *         type="array",
 *         @SWG\Items(ref="#/definitions/Link")
 *     ),
 *     @SWG\Property(
 *         property="referral",
 *         ref="#/definitions/Referral",
 *     ),
 *     @SWG\Property(
 *         property="videos",
 *         type="array",
 *         @SWG\Items(ref="#/definitions/Video")
 *     ),
 *     @SWG\Property(
 *         property="partners",
 *         type="array",
 *         @SWG\Items(ref="#/definitions/Partner")
 *     ),
 *     @SWG\Property(
 *         property="balance",
 *         ref="#/definitions/BalanceTop",
 *     ),
 *     @SWG\Property(
 *         property="entertainment",
 *         ref="#/definitions/EntertainmentTop",
 *     ),
 *
 * ),
 * @SWG\Definition(
 *     definition="VideoZone",
 *     required={"video_limit", "videos",},
 *     @SWG\Property(
 *         property="video_limit",
 *         ref="#/definitions/VideoLimit"
 *     ),
 *     @SWG\Property(
 *         property="videos",
 *         type="array",
 *         @SWG\Items(ref="#/definitions/Video")
 *     ),
 *
 * ),
 * @SWG\Definition(
 *     definition="Users_Marathon",
 *     required={"id", "title", "all_days", "current_day",
 *     "award", "pivot"},
 *     @SWG\Property(
 *         property="id",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="title",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="all_days",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="current_day",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="award",
 *         type="number"
 *     ),
 *     @SWG\Property(
 *         property="pivot",
 *         ref="#/definitions/Pivot_m"
 *     ),
 * ),
 * @SWG\Definition(
 *     definition="Pivot_m",
 *     required={"times", "failed", "is_available"},
 *     @SWG\Property(
 *         property="times",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="is_available",
 *         type="boolean"
 *     ),
 *     @SWG\Property(
 *         property="failed",
 *         type="boolean"
 *     ),
 *  ),
 * @SWG\Definition(
 *     definition="Marathon",
 *     required={"id", "title", "all_days", "current_day",
 *     "award"},
 *     @SWG\Property(
 *         property="id",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="title",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="all_days",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="current_day",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="award",
 *         type="number"
 *     ),
 * ),
 * @SWG\Definition(
 *     definition="Users_Task",
 *     required={"id", "package_name", "title", "image_url", "description", "duration", "award", "daily_award",
 *     "type", "days", "time_delay", "keywords", "pivot_t"},
 *     @SWG\Property(
 *         property="id",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="package_name",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="title",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="image_url",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="description",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="duration",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="award",
 *         type="number"
 *     ),
 *      @SWG\Property(
 *         property="daily_award",
 *         type="number"
 *     ),
 *     @SWG\Property(
 *         property="type",
 *         type="integer"
 *     ),
 *      @SWG\Property(
 *         property="days",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="time_delay",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="keywords",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="available_time",
 *         description="time when task can be run again",
 *         example="2019-01-09 12:09:29",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="pivot",
 *         ref="#/definitions/Pivot_t"
 *     ),
 * ),
 * @SWG\Definition(
 *     definition="Pivot_t",
 *     required={"times", "failed_times", "is_available", "is_rating_available"},
 *     @SWG\Property(
 *         property="times",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="failed_times",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="is_available",
 *         type="boolean"
 *     ),
 *     @SWG\Property(
 *         property="is_rating_available",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="cards",
 *         type="array",
 *         @SWG\Items(type="integer")
 *     ),
 *     @SWG\Property(
 *         property="progress_bar",
 *         type="array",
 *         @SWG\Items(type="integer")
 *     ),
 *
 *  ),
 * @SWG\Definition(
 *     definition="UserLevel",
 *     required={"level", "stars", "task", "video", "partner", "referral"},
 *     @SWG\Property(
 *         property="level",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="stars",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="task",
 *         type="array",
 *         @SWG\Items(type="integer")
 *     ),
 *     @SWG\Property(
 *         property="video",
 *         type="array",
 *         @SWG\Items(type="integer")
 *     ),
 *     @SWG\Property(
 *         property="partner",
 *         type="array",
 *         @SWG\Items(type="integer")
 *     ),
 *     @SWG\Property(
 *         property="referral",
 *         type="array",
 *         @SWG\Items(type="integer")
 *     ),
 *
 *  ),
 * @SWG\Definition(
 *     definition="RateAward",
 *     required={"task", "video", "partner", "referral"},
 *     @SWG\Property(
 *         property="task",
 *         type="number"
 *     ),
 *     @SWG\Property(
 *         property="video",
 *         type="number"
 *     ),
 *     @SWG\Property(
 *         property="partner",
 *         type="number"
 *     ),
 *     @SWG\Property(
 *         property="referral",
 *         type="integer"
 *     ),
 *
 *  ),
 * @SWG\Definition(
 *     definition="BonusCard",
 *     required={"id", "type", "bonus", "stars", "special"},
 *     @SWG\Property(
 *         property="id",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="type",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="bonus",
 *         type="number"
 *     ),
 *     @SWG\Property(
 *         property="stars",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="special",
 *         type="array",
 *         @SWG\Items(type="integer")
 *     ),
 *
 *  ),
 * @SWG\Definition(
 *     definition="Video",
 *     description=". Where id 1 = admob, 2 = fyber",
 *     required={"id", "title", "limit", "award", "limit", "image_url", "pivot_v"},
 *     @SWG\Property(
 *         property="id",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="title",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="limit",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="award",
 *         type="number"
 *     ),
 *     @SWG\Property(
 *         property="image_url",
 *         type="string",
 *         example="http://localhost:8080/images/videos/fyber-logo.png",
 *     ),
 *     @SWG\Property(
 *         property="pivot",
 *         ref="#/definitions/Pivot_v"
 *     ),
 *
 *  ),
 * @SWG\Definition(
 *     definition="Pivot_v",
 *     required={"views", "today_views", "earned", "is_available"},
 *     @SWG\Property(
 *         property="views",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="today_views",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="earned",
 *         type="number"
 *     ),
 *     @SWG\Property(
 *         property="is_available",
 *         type="boolean"
 *     ),
 *
 *  ),
 * @SWG\Definition(
 *     definition="VideoLimit",
 *     required={"limit", "today_viewed"},
 *     @SWG\Property(
 *         property="limit",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="today_viewed",
 *         type="integer"
 *     ),
 *
 *  ),
 * @SWG\Definition(
 *     definition="Partner",
 *     required={"id", "title", "description", "award", "pivot"},
 *     @SWG\Property(
 *         property="id",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="title",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="description",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="award",
 *         type="number"
 *     ),
 *      @SWG\Property(
 *         property="image_url",
 *         type="string"
 *     ),
 *
 *  ),
 *  @SWG\Definition(
 *     definition="Pivot_p",
 *     required={"times", "earned"},
 *     @SWG\Property(
 *         property="times",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="earned",
 *         type="number"
 *     ),
 *
 *  ),
 *  @SWG\Definition(
 *     definition="Referral",
 *     required={"description"},
 *     @SWG\Property(
 *         property="description",
 *         type="string"
 *     ),
 *
 *  ),
 *  @SWG\Definition(
 *     definition="BalanceTop",
 *     required={"description"},
 *     @SWG\Property(
 *         property="description",
 *         type="string"
 *     ),
 *
 *  ),
 * @SWG\Definition(
 *     definition="EntertainmentTop",
 *     required={"description"},
 *     @SWG\Property(
 *         property="description",
 *         type="string"
 *     ),
 *
 *  ),
 * @SWG\Definition(
 *     definition="Country",
 *     required={"id", "country_name_ru", "country_name_en"},
 *     @SWG\Property(
 *         property="id",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="country_name_ru",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="country_name_en",
 *         type="string"
 *     ),
 *
 *  ),
 * * @SWG\Definition(
 *     definition="ReferralInfo",
 *     required={"referrals", "balance", "award", "paid"},
 *     @SWG\Property(
 *         property="referrals",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="balance",
 *         type="number"
 *     ),
 *     @SWG\Property(
 *         property="award",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="paid",
 *         type="number"
 *     ),
 *
 * ),
 * @SWG\Definition(
 *     definition="ReferralHistory",
 *     required={"paid", "email", "date"},
 *     @SWG\Property(
 *         property="paid",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="email",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="date",
 *         type="string"
 *     ),
 *
 * ),
 * @SWG\Definition(
 *     definition="TransactionHistory",
 *     required={"method", "amount_clean", "state", "date"},
 *     @SWG\Property(
 *         property="method",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="amount_clean",
 *         type="number"
 *     ),
 *     @SWG\Property(
 *         property="state",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="date",
 *         type="string"
 *     ),
 *
 * ),
 * @SWG\Definition(
 *     definition="GetCardsTransaction",
 *     required={"rate", "top", "cards"},
 *     @SWG\Property(
 *         property="rate",
 *         type="number"
 *     ),
 *     @SWG\Property(
 *         property="top",
 *         type="array",
 *         @SWG\Items(ref="#/definitions/CardTransaction")
 *     ),
 *     @SWG\Property(
 *         property="cards",
 *         type="array",
 *         @SWG\Items(ref="#/definitions/CardTransaction")
 *     ),
 *
 * ),
 * @SWG\Definition(
 *     definition="CardTransaction",
 *     required={"id", "title"},
 *     @SWG\Property(
 *         property="id",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="title",
 *         type="string"
 *     ),
 *
 * ),
 * @SWG\Definition(
 *     definition="UserCardTransaction",
 *     required={"id", "title", "pivot"},
 *     @SWG\Property(
 *         property="id",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="title",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="pivot",
 *         ref="#/definitions/Pivot_c_t"
 *     ),
 *
 * ),
 * @SWG\Definition(
 *     definition="Pivot_c_t",
 *     required={"ud", "amount"},
 *     @SWG\Property(
 *         property="ud",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="amount",
 *         type="number"
 *     ),
 *
 *  ),
 * @SWG\Definition(
 *     definition="Quiz",
 *     required={"id", "title", "pivot"},
 *     @SWG\Property(
 *         property="id",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="title",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="pivot",
 *         ref="#/definitions/Pivot_q"
 *     ),
 *
 *  ),
 * @SWG\Definition(
 *     definition="Pivot_q",
 *     required={"today_times", "limit", "times", "earned", "is_available"},
 *     @SWG\Property(
 *         property="today_views",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="limit",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="times",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="earned",
 *         type="number"
 *     ),
 *     @SWG\Property(
 *         property="is_available",
 *         type="boolean"
 *     ),
 *
 *  ),
 * @SWG\Definition(
 *     definition="QuizQuestion",
 *     required={"id", "question", "A", "B", "C", "D", "correct_answer"},
 *     @SWG\Property(
 *         property="id",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="question",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="A",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="B",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="C",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="D",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="correct_answer",
 *         type="string"
 *     ),
 *
 *  ),
 * @SWG\Definition(
 *     definition="Game",
 *     required={"id", "title", "pivot"},
 *     @SWG\Property(
 *         property="id",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="title",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="pivot",
 *         ref="#/definitions/Pivot_g"
 *     ),
 *
 *  ),
 * @SWG\Definition(
 *     definition="Pivot_g",
 *     required={"today_times", "limit", "times", "earned", "best_score","is_available"},
 *     @SWG\Property(
 *         property="today_views",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="limit",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="times",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="earned",
 *         type="number"
 *     ),
 *     @SWG\Property(
 *         property="best_score",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="is_available",
 *         type="boolean"
 *     ),
 *
 *  ),
 * @SWG\Definition(
 *     definition="Questions",
 *     required={"quiz_id","questions"},
 *     @SWG\Property(
 *         property="quiz_id",
 *         type="integer",
 *     ),
 *     @SWG\Property(
 *         property="questions",
 *         type="array",
 *         @SWG\Items(ref="#/definitions/QuizQuestion")
 *     ),
 *
 * ),
 * @SWG\Definition(
 *     definition="CardTransactionProgressBar",
 *     required={"goal", "progress"},
 *     @SWG\Property(
 *         property="goal",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="progress",
 *         type="integer"
 *     ),
 *
 *  ),
 */
