<?php
/**
 * @SWG\Definition(
 *     definition="ProfileResponse",
 *     required={"username","email","phone","gender"},
 *     @SWG\Property(
 *          property="profile",
 *          ref="#/definitions/Profile",
 *     ),
 *     @SWG\Property(
 *          property="progress",
 *          ref="#/definitions/Progress",
 *     ),
 *     ),
 * @SWG\Definition(
 *     definition="Profile",
 *     required={"username","email","phone","gender"},
 *     @SWG\Property(
 *          property="username",
 *          type="string",
 *          example="Jon",
 *     ),
 *     @SWG\Property(
 *          property="email",
 *          type="string",
 *          example="jon@gmail.com",
 *     ),
 *     @SWG\Property(
 *          property="phone",
 *          type="string",
 *          example="+380966666666",
 *     ),
 *     @SWG\Property(
 *          property="gender",
 *          type="string",
 *          example="female",
 *     ),
 * ),
 *
 * @SWG\Definition(
 *     definition="Progress",
 *     required={"profile","tasks","videos","partners","referals"},
 *     @SWG\Property(
 *          property="profile",
 *          ref="#/definitions/ProgressItem",
 *     ),
 *     @SWG\Property(
 *          property="tasks",
 *          ref="#/definitions/ProgressItem",
 *     ),
 *     @SWG\Property(
 *          property="videos",
 *          ref="#/definitions/ProgressItem",
 *     ),
 *     @SWG\Property(
 *          property="partners",
 *          ref="#/definitions/ProgressItem",
 *     ),
 *     @SWG\Property(
 *          property="referals",
 *          ref="#/definitions/ProgressItem",
 *     ),
 * ),
 * @SWG\Definition(
 *     definition="ProgressItem",
 *     required={"level","current","max","percent"},
 *     @SWG\Property(
 *          property="level",
 *          type="integer",
 *          example=1,
 *     ),
 *     @SWG\Property(
 *          property="current",
 *          type="integer",
 *          example=2,
 *     ),
 *     @SWG\Property(
 *          property="max",
 *          type="integer",
 *          example=3,
 *     ),
 *     @SWG\Property(
 *          property="percent",
 *          type="integer",
 *          example=60,
 *     ),
 * );
 * @SWG\Get(
 *     path="/api/v1/profile",
 *     summary="Get profile data.",
 *     tags={"profiles"},
 *     operationId="profile",
 *     produces={"application/json"},
 *     @SWG\Parameter(
 *          name="token",
 *          in="header",
 *          description="token",
 *          required=true,
 *          type="string",
 *      ),
 *      @SWG\Response(
 *         response=200,
 *         description="Successful operation, profile data provided.",
 *         @SWG\Schema(
 *             type="object",
 *             ref="#/definitions/ProfileResponse"
 *         )
 *      ),
 *     @SWG\Response(
 *         response=401,
 *         description="Wrong token.",
 *      ),
 *     );
 * @SWG\Post(
 *     path="/api/v1/profile",
 *     summary="Get profile data.",
 *     tags={"profiles"},
 *     operationId="profile",
 *     consumes={"application/json"},
 *     produces={"application/json"},
 *     @SWG\Parameter(
 *          name="token",
 *          in="header",
 *          description="token for authentificathion",
 *          required=true,
 *          type="string",
 *      ),
 *     @SWG\Parameter(
 *          name="username",
 *          in="body",
 *          description="username",
 *          @SWG\Schema(
 *              type="string",
 *              example="Jon",
 *          ),
 *     ),
 *     @SWG\Parameter(
 *          name="phone",
 *          in="body",
 *          description="user Phone number.",
 *          @SWG\Schema(
 *              type="string",
 *              example="+380969999999",
 *          ),
 *     ),
 *     @SWG\Parameter(
 *          name="gender",
 *          in="body",
 *          description="can be 'male' or 'female'",
 *          @SWG\Schema(
 *              type="string",
 *              example="female",
 *          ),
 *     ),
 *     @SWG\Response(
 *         response=200,
 *         description="Successful operation, profile data provided.",
 *
 *      ),
 *     @SWG\Response(
 *         response=401,
 *         description="Wrong token.",
 *      ),
 *     @SWG\Response(
 *         response=422,
 *         description="Wrong data format.",
 *      ),
 *     );
 */
